name: CI/CD Backend Despachos

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen
        uses: docker/build-push-action@v5
        with:
          context: ./Springboot-API-REST-DESPACHO
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/back-despachos:latest

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          proxy_host: ${{ secrets.EC2_BACKEND_HOST }}
          proxy_username: ${{ secrets.EC2_USER }}
          proxy_key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/back-despachos:latest
            sudo docker stop backend_despachos || true
            sudo docker rm backend_despachos || true
            sudo docker run -d \
              --name backend_despachos \
              --restart unless-stopped \
              -p 8081:8081 \
              --link mysql_despachos:mysql \
              -e DB_ENDPOINT=mysql \
              -e DB_PORT=3306 \
              -e DB_NAME=despachos_db \
              -e DB_USERNAME=appuser \
              -e DB_PASSWORD=apppassword \
              -e SPRING_DATASOURCE_URL="jdbc:mysql://mysql:3306/despachos_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true" \
              ${{ secrets.DOCKERHUB_USERNAME }}/back-despachos:latest
